apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-deployment
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      tag: {{ .Values.tag}}
  template:
    metadata:
      labels:
        tag: {{ .Values.tag}}
    spec:
      containers:
      - name: final-container
        image: final:v1

